apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
        - name: demo-api
          image: demo-api:latest  
            - containerPort: 8088
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:h2:mem:testdb
            - name: SPRING_DATASOURCE_DRIVER_CLASSNAME
              value: org.h2.Driver
            - name: SPRING_DATASOURCE_USERNAME
              value: sa
            - name: SPRING_DATASOURCE_PASSWORD
              value:
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: org.hibernate.dialect.H2Dialect
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_H2_CONSOLE_ENABLED
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-api-service
spec:
  selector:
    app: demo-api
  ports:
    - protocol
